# Generated by Django 4.2.27 on 2026-01-04 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the conversation', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the conversation was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last message in the conversation')),
                ('participants', models.ManyToManyField(help_text='Users participating in this conversation', related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'db_table': 'conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the message', primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Message content (max 2000 characters)', max_length=2000)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the message was sent')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the message has been read')),
                ('conversation', models.ForeignKey(help_text='Conversation this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
                ('sender', models.ForeignKey(help_text='User who sent the message', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Private Message',
                'verbose_name_plural': 'Private Messages',
                'db_table': 'private_messages',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['conversation', 'timestamp'], name='private_mes_convers_09b53b_idx'), models.Index(fields=['sender', 'timestamp'], name='private_mes_sender__4aebb0_idx')],
            },
        ),
        migrations.CreateModel(
            name='GlobalMessage',
            fields=[
                ('id', models.BigAutoField(help_text='Auto-increment ID for performance', primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Message content (max 2000 characters)', max_length=2000)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the message was sent')),
                ('sender', models.ForeignKey(help_text='User who sent the message', on_delete=django.db.models.deletion.CASCADE, related_name='global_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Global Message',
                'verbose_name_plural': 'Global Messages',
                'db_table': 'global_messages',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='global_mess_timesta_bbcdb7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('id',), name='unique_conversation_id'),
        ),
    ]
